/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rulewerk_clingo_TermQueryResultIterator */

#ifndef _Included_rulewerk_clingo_TermQueryResultIterator
#define _Included_rulewerk_clingo_TermQueryResultIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rulewerk_clingo_TermQueryResultIterator
 * Method:    hasNext
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_rulewerk_clingo_TermQueryResultIterator_hasNext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     rulewerk_clingo_TermQueryResultIterator
 * Method:    next
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_rulewerk_clingo_TermQueryResultIterator_next
  (JNIEnv *, jobject, jlong);

/*
 * Class:     rulewerk_clingo_TermQueryResultIterator
 * Method:    remove
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_rulewerk_clingo_TermQueryResultIterator_remove
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
