/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rulewerk_clingo_Clingo */

#ifndef _Included_rulewerk_clingo_Clingo
#define _Included_rulewerk_clingo_Clingo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rulewerk_clingo_Clingo
 * Method:    startSolver
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_rulewerk_clingo_Clingo_startSolver
  (JNIEnv *, jobject);

/*
 * Class:     rulewerk_clingo_Clingo
 * Method:    stopSolver
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_rulewerk_clingo_Clingo_stopSolver
  (JNIEnv *, jobject);

/*
 * Class:     rulewerk_clingo_Clingo
 * Method:    initPart
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_rulewerk_clingo_Clingo_initPart
  (JNIEnv *, jobject, jstring);

/*
 * Class:     rulewerk_clingo_Clingo
 * Method:    getPart
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_rulewerk_clingo_Clingo_getPart
  (JNIEnv *, jobject, jstring);

/*
 * Class:     rulewerk_clingo_Clingo
 * Method:    addRule
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_rulewerk_clingo_Clingo_addRule
  (JNIEnv *, jobject, jstring);

/*
 * Class:     rulewerk_clingo_Clingo
 * Method:    addRules
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_rulewerk_clingo_Clingo_addRules
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     rulewerk_clingo_Clingo
 * Method:    addData
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_rulewerk_clingo_Clingo_addData
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     rulewerk_clingo_Clingo
 * Method:    ground
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_rulewerk_clingo_Clingo_ground
  (JNIEnv *, jobject);

/*
 * Class:     rulewerk_clingo_Clingo
 * Method:    solve
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_rulewerk_clingo_Clingo_solve
  (JNIEnv *, jobject);

/*
 * Class:     rulewerk_clingo_Clingo
 * Method:    getRule
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_rulewerk_clingo_Clingo_getRule
  (JNIEnv *, jobject);

/*
 * Class:     rulewerk_clingo_Clingo
 * Method:    printModel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_rulewerk_clingo_Clingo_printModel
  (JNIEnv *, jobject);

/*
 * Class:     rulewerk_clingo_Clingo
 * Method:    termQuery
 * Signature: (Ljava/lang/String;)Lrulewerk/clingo/TermQueryResultIterator;
 */
JNIEXPORT jobject JNICALL Java_rulewerk_clingo_Clingo_termQuery
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
